### ISSUE TITLE
Improved EC2 Spot Instances support in kops

### ISSUE THREAD

**Issue by schmutze** [aws/ec2-spot-instances-integrations-roadmap#3]
We are working on a [kops](https://github.com/kubernetes/kops) "one click EC2 Spot Instances setup" designed to get customers up-and-running quickly with utilizing EC2 Spot Instances best practices when running Kubernetes on AWS. 

Visit the PR here:
https://github.com/kubernetes/kops/pull/9478

**Comment by bwagner5** [comment]
https://github.com/kubernetes/kops/pull/9478 integrates kOps with the [https://github.com/aws/amazon-ec2-instance-selector](ec2-instance-selector) so that you can specify the resources your k8s nodes require, like vcpus and memory. kOps will generate an InstanceGroup config with the instance types that match the resource criteria you specified. 

You can also use the `--usage-class spot` flag to generate a kOps InstanceGroup config that utilizes spot best practices like using the capacity-optimized allocation strategy. 

The integration is exposed in kOps as a new toolbox command:

```
$ kops toolbox instance-selector demo --dry-run --base-instance-type c5.4xlarge --usage-class spot --name demo-0a20f32c.kops.sh
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: demo-0a20f32c.kops.sh
  name: test
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/demo-0a20f32c.kops.sh: "1"
    k8s.io/cluster-autoscaler/enabled: "1"
    kops.k8s.io/instance-selector: "1"
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-11-19
  machineType: c3.4xlarge
  maxSize: 10
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - c3.4xlarge
    - c4.4xlarge
    - c5.4xlarge
    - c5a.4xlarge
    - c5ad.4xlarge
    - c5d.4xlarge
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/instancegroup: test
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
```

kops toolbox instance-selector is available in kops versions 1.19+
