### ISSUE TITLE
EC2 Spot Instances best practices support in Spark on K8s

### ISSUE THREAD

**Issue by schmutze** [aws/ec2-spot-instances-integrations-roadmap#8]
We are working on a project to support EC2 Spot Instances best practices while running Spark on Kubernetes on AWS.

We'd love to hear your requirements and feedback on this project!

**Comment by stijndehaes** [comment]
Well this issue is pretty bare bones. But we have been running Spark on Kubernetes (EKS) for a while now with spot instances. The biggest issue we had were wrongly configure launch templates were we took the lowest price strategy and not capacity optimized. With capacity optimized most of our struggles are over. We are waiting for an external shuffle service to run for spark on kubernetes so we can have dynamic scaling and also that crashing your executors is not that bad. At the moment your job has to start all over again.

**Comment by dchelupati** [comment]
> Well this issue is pretty bare bones. But we have been running Spark on Kubernetes (EKS) for a while now with spot instances. The biggest issue we had were wrongly configure launch templates were we took the lowest price strategy and not capacity optimized. With capacity optimized most of our struggles are over. We are waiting for an external shuffle service to run for spark on kubernetes so we can have dynamic scaling and also that crashing your executors is not that bad. At the moment your job has to start all over again.

Hi, Thanks for your feedback. Can you help us understand what was biggest challenge in using Spark jobs on EKS with Spot instances? Also, elaborate on need for dynamic scaling, what are limitations today? Also, are you referring to the executors crashing and job restarts are when K8s nodes with Spot are interrupted?

**Comment by stijndehaes** [comment]
So when we were running lowest price, we had a lot of problems with stability because of losing executors. 
So yes I am referring to executors crashing and job restart when k8s nodes are interrupted. Because spark on kubernetes does not store it's intermediate results anywhere persistent but on a local dir on the node this can be a big pain. By using capacity optimized you get a lot less interrupts and this problem is less of an issue. So I would recommend people running capacity optimized since spark can handle interrupts but if you get a lot of them your job will cost more then running on demand because of all the retries.

Before spark 3.0 you couldn't even run dynamic execution on kubernetes but since spark 3.0 you can. However same problems apply with intermediate not being store anywhere persistent so not always usable (this is not fault of aws however)>

**Comment by dchelupati** [comment]
That is very helpful. Can you share details on your setup? do you first configure the EKS cluster with worker nodes on Spot ASGs and then use Spark submit to run the jobs? do you use multiple instance types/mixed instance policies with Spot worker nodes? how do you determine the size of worker nodes and size of executors [CPU/memory], which one comes first? do your spark jobs typically need same CPU/mem requirements? when your worker nodes don't meet job requirements, how do you modify the instance types? is this worker node setup used for other workloads or purely for Spark only?

**Comment by dchelupati** [comment]
> So when we were running lowest price, we had a lot of problems with stability because of losing executors.
> So yes I am referring to executors crashing and job restart when k8s nodes are interrupted. Because spark on kubernetes does not store it's intermediate results anywhere persistent but on a local dir on the node this can be a big pain. By using capacity optimized you get a lot less interrupts and this problem is less of an issue. So I would recommend people running capacity optimized since spark can handle interrupts but if you get a lot of them your job will cost more then running on demand because of all the retries.
> Before spark 3.0 you couldn't even run dynamic execution on kubernetes but since spark 3.0 you can. However same problems apply with intermediate not being store anywhere persistent so not always usable (this is not fault of aws however)>

That is very helpful. Can you share details on your setup? do you first configure the EKS cluster with worker nodes on Spot ASGs and then use Spark submit to run the jobs? do you use multiple instance types/mixed instance policies with Spot worker nodes? how do you determine the size of worker nodes and size of executors [CPU/memory], which one comes first? do your spark jobs typically need same CPU/mem requirements? when your worker nodes don't meet job requirements, how do you modify the instance types? is this worker node setup used for other workloads or purely for Spark only?

**Comment by stijndehaes** [comment]
> That is very helpful. Can you share details on your setup? do you first configure the EKS cluster with worker nodes on Spot ASGs and then use Spark submit to run the jobs? do you use multiple instance types/mixed instance policies with Spot worker nodes? how do you determine the size of worker nodes and size of executors [CPU/memory], which one comes first? do your spark jobs typically need same CPU/mem requirements? when your worker nodes don't meet job requirements, how do you modify the instance types? is this worker node setup used for other workloads or purely for Spark only?

So we configure an EKS cluster with workers nodes on spot ASGs. We use a launch templates with mixed instance policy however each of these instances are 4 cpu's and 16gb memory (because of kubernetes daemonset overhead using smaller instances does not make sense). So we use `"m5.xlarge", "m4.xlarge", "m5d.xlarge", "m5n.xlarge", "m5dn.xlarge", "m5a.xlarge"` which all have the same cpu/memory profile. The reason for this is that kubernetes autoscaler (used to autoscaling our ASG groups) expects all instances in one ASG to have the same resources/ The added storage on d instances goes wasted but that is fine since we use spot instances.

We then use spark submit through airflow to schedule jobs (airflow also running on k8s). The size of executors we let people choose freely but recommend either 1cpu 4gb or 3 cpu's 12gb. Reason for that is to pack nodes better. Because we have added overhead of daemonset's we can't use the full cpu's (or we have to set these daemonsets to use 0cpu meaning they can get starved for CPU cycles haven't tested that though). Jobs using 2cpu are wasteful unless you have another job fitting the leftover. So we are searching for a good way to allow spark to use part of this extra core without hurting the daemonsets. Probably we will do something when you ask for four cpu's you set the requests of the pod to 3.5 and allow it to burst to 4. That way kubernetes should still allow daemonsets to get their requested CPU but then you need to be sure you set this correctly ofcourse.

It's a mixed setup for airflow spark, and we run other jobs on it too. But most of it is spark atm.

For supporting bigger spark setups we need to configure new ASG's with bigger instances and probably we want to limit which spark pods land on which nodes trough taints and tolerations. This is not yet setup however with spark 3.0 pod templates this is now possible. That way we can make sure small jobs don't land on big nodes and keep these nodes up without using them fully.

Sorry about this long text I hope I made myself somewhat clear :)

**Comment by dchelupati** [comment]
Thanks again and I do appreciate the long text as it helps me walk through your journey. Between the ability to ensure jobs are running on right size worker nodes vs job restarts due to intermediate data being stored on the nodes themselves, which one is most painful for you? what are some other pain points that exist that we should know of? If you were starting all over and were looking to figure out how to run Spark on K8s Spot worker nodes, what would have been helpful at that time?

**Comment by stijndehaes** [comment]
Using capacity-optimized allocation strategy was a big win for us. This dropped interruptions significantly and freed us up from investigating or restarting stuff. Using spot is always a balance between engineering cost and instance cost. And I don't know if we were breaking even but since we use capacity-optimized we don't look back. Sure it costs a bit more but we don't run into problems anymore. This was the biggest change for us.

Right size worker nodes is not much of a problem, most of our jobs are effectively small data. Most of the big data jobs have enough using 10 x 3cpu 12gb memory so that is fine. But might be different for different people ;)

I would suggest other people to start with 4cpu, 16gb nodes with capacity-optimized and start from there. For most people and most spark jobs this will be fine I guess. But that is an assumption ofcourse.
